<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>inflasi thd pert ekonomi</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="abxc_files/libs/clipboard/clipboard.min.js"></script>
<script src="abxc_files/libs/quarto-html/quarto.js"></script>
<script src="abxc_files/libs/quarto-html/popper.min.js"></script>
<script src="abxc_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="abxc_files/libs/quarto-html/anchor.min.js"></script>
<link href="abxc_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="abxc_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="abxc_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="abxc_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="abxc_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">inflasi thd pert ekonomi</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="analisis-pengaruh-tingkat-inflasi-terhadap-pertumbuhan-ekonomi-di-indonesia" class="level2">
<h2 class="anchored" data-anchor-id="analisis-pengaruh-tingkat-inflasi-terhadap-pertumbuhan-ekonomi-di-indonesia">ANALISIS PENGARUH TINGKAT INFLASI TERHADAP PERTUMBUHAN EKONOMI DI INDONESIA</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Logo%20app.jpg" class="img-fluid figure-img"></p>
</figure>
</div>
<p><strong>Jian Maulia J (210203777)</strong></p>
<p><strong>PIWAR 3D</strong></p>
</section>
<section id="bab-i-pendahuluan" class="level1">
<h1>Bab I Pendahuluan</h1>
<section id="latar-belakang" class="level2">
<h2 class="anchored" data-anchor-id="latar-belakang">1.1&nbsp; Latar Belakang</h2>
<p>Apa itu inflasi?, Inflasi merupakan suatu proses meningkatnya harga-harga secara umum dan terus-menerus, kenaikan harga dari satu atau dua barang saja tidak dapat disebut inflasi kecuali bila kenaikan itu meluas pada barang lainnya, atau menurunnya nilai uang kertas terhadap mata uang asing karena banyaknya dan cepatnya uang kertas beredar.<strong>Inflasi</strong> sendiri biasa disebabkan oleh banyaknya jumlah uang yang beredar dan seiring berjalannya waktu akan naik dua kali lipat maka harga juga akan naik dua kali lipat. Penambahan jumlah uang yang beredar dapat terjadi misalnya kalau pemerintah memakai sistem anggaran defisit, menurut data yang diolah oleh bola salju ,</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/inflasi-20-tahun-rev.jpeg" class="img-fluid figure-img" width="404"></p>
</figure>
</div>
<p>Selama 20 tahun ini indonesia telah mengalami akumulasi nilai inflasi sebesar 200,45% dalam kurun waktu 20 tahun dan 5,84% per tahunnya.</p>
<p>Sementara itu Pertumbuhan ekonomi sendiri merupakan peningkatan dalam kemampuan dari suatu perekonomian dalam memproduksi barang dan jasa. yang artinya jika suatu negara memiliki pertumbuhan ekonomi yang begitu cepat tingkat produksi barang dan jasanya pun akan ikut meningkat, begitu pula dengan konsumsi masyarakatnya dengan secara otomatis akan menikan GDP mereka sedikit demi sedikit seiring dengannya meingkatnya pertumbuhan ekonomi.</p>
</section>
<section id="batasan-masalah" class="level2">
<h2 class="anchored" data-anchor-id="batasan-masalah">1.2&nbsp; Batasan Masalah</h2>
<p>Batasan masalah kali ini terfokus pada pengaruh inflasi terhadap pertumbuhan ekonomi dan sebaliknya dari dua variabel terkait. untuk menghindari luasnya topik bahasan yang nanti akan dilakukan serta agar pembaca tidak merasa bingung tentang arah bahasan yang saya lakukan.</p>
</section>
<section id="rumusan-masalah" class="level2">
<h2 class="anchored" data-anchor-id="rumusan-masalah">1.3&nbsp; Rumusan Masalah</h2>
<p>Dari latar belakang yang sudah diuraikan di atas kita dapat melihat 2 rumusan masalah, antara lain:</p>
<ol type="1">
<li>Apakah inflasi berpengaruh terhadap pertumbuhan ekonomi?</li>
<li>Apakah pertumbuhan ekonomi bergantung penuh pada inflasi?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level2">
<h2 class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian">1.4&nbsp; Tujuan dan Manfaat Penelitian</h2>
<p>Makalah ini dibuat dengan tujuan untuk memenuhi kewajiban saya sebagai mahasiswa untuk mata kuliah Metodologi Penelitian,yang diampu oleh bapak “imed” &amp; ibu “tere’ selama periode 2022/2023 atau saat semester ganjil pada angkatan kedua di Politeknik APP Jakarta. dan juga agar para pembaca seperti masayarakat umum dan mahasiswa dapat terbantu dengan adanya makalah ini dan bisa menjadi acuan untuk membuat makalah lainnya.</p>
<p>Manfaat dari penelitian ini sendiri adalah memberikan informasi terhadap pembaca di luar sana yang tidak sempat mencari data secara spesifik atau tidak memiliki waktu luang untuk mendengarkan berita serta makalah ini bermanfaat untuk mnambah wawasan para pembaca dengan pembahasaan yang tidak terlalu rumit dan dengan penyampaian yang informal.</p>
</section>
</section>
<section id="section" class="level1">
<h1></h1>
</section>
<section id="bab-ii-studi-pustaka" class="level1">
<h1>Bab II Studi Pustaka</h1>
<section id="teori-i" class="level2">
<h2 class="anchored" data-anchor-id="teori-i">2.1 Teori I</h2>
<p>Dari yang kita tahun indonesia sendiri Inflasi adalah suatu gejala dimana tingkat harga umum mengalami kenaikan secara terus menerus. Kenaikan harga dari satu dua barang saja tidak dapat disebut inflasi, kecuali bila kenaikan tersebut meluas kepada (atau mengakibatkan kenaikan) sebagian besar dari harga barang-barang lain (Boediono, 2014:161). Inflasi adalah naiknya harga harga komoditi secara umum yang disebabkan oleh tidak sinkronnya antara program pengadaan komoditi (produksi, penentuan harga, pencetakan uang, dan sebagainya) dengan tingkat pendapatan yang dimiliki oleh masyarakat (Putong, 2013:147).</p>
</section>
<section id="teori-ii" class="level2">
<h2 class="anchored" data-anchor-id="teori-ii">2.2 Teori II</h2>
<p>Pertumbuhan ekonomi Bagi suatu negara, pertumbuhan ekonomi menjadi salah satu fokus yang harus dicapai di setiap tahunnya. Angka pertumbuhan ekonomi di suatu negara akan menjadi salah satu tolak ukur keberhasilan. Hal tersebut juga menjadi salah satu fokus bagi negara Indonesia. Menurut M. Suparko dan Maria R. Suparko ada beberapa macam alat yang dapat digunakan untuk mengukur pertumbuhan ekonomi yaitu :</p>
<p>a. Produk Domestik Bruto</p>
<p>PDB adalah jumlah barang dan jasa akhir yang dihasilkan dalam harga pasar. Kelemahan PDB sebagai ukuran pertumbuhan ekonomi adalah sifatnya yang global dan tidak mencerminkan kesejahteraan penduduk.</p>
<p>b. PDB per Kapita atau Pendapatan Perkapita</p>
<p>PDB per kapita merupakan ukuran yang lebih tepat karean telah memperhitungkan jumlah penduduk. Jadi ukuran pendapatn perkapita dapat diketahui dengan membagi PDB dengan jumlah penduduk.</p>
<p>c. Pendapatan Per jam Kerja</p>
<p>Suatu negara dapat dikatakan lebih maju dibandingkan negara lain bila mempunyai tingkat pendapatan atau upah per jam kerja yang lebih tinggi daripada upah per jam kerja di negara lain untuk jenis pekerjaan yang sama.</p>
</section>
<section id="kerangka-penelitian" class="level2">
<h2 class="anchored" data-anchor-id="kerangka-penelitian">2.3 Kerangka Penelitian</h2>
<p>&nbsp; Pada penelitian ini penulis akan melakukan penelitian dengan alat bantu yaitu Rstudio dan R serta dengan bahan yang didapat dari sumber yang dipercaya seperti BPS dan Bank Indoneisa, materi dan alur penelitian dibuat dengan sistematis sehingga dapat menjadi acuan untuk memecahkan masalah.</p>
</section>
</section>
<section id="bab-iii-metode-penelitian" class="level1">
<h1>Bab III Metode Penelitian</h1>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">3.1 Data</h2>
<p><img src="images/tabel.jpeg" class="img-fluid"></p>
<p>Data yang diambil ini sudah diformat ke dalam excel dan agar lebih mudah dibaca dan kedua variabel tersebut merupakan data inflasi (X) dari tahun 2012<em>(tabel no 1)</em> sampai 2022<em>(tabel no 11)</em>, jika dilihat data inflasi selama 10 tahun tersebut bisa dibilang cukup fluktuatif, dan tidak terlalu stabil, kestabilan tersebut hanya dapat bertahan beberapa tahun saja sampai kemudian inflasi terbeut naik atau turun kembali, sejauh yang bisa kita lihat bahwa pada tahun 2013 dan 2014 <em>(tabel no 2 dan 3 ),</em> memiliki persentase yang paling tinggi, sementara inflasi yang paling rendah yaitu pada tahun 2020 yang hanya 1,6% saja. Sementara untuk pertumbuhan ekonomi sendiri jika kita melihat dari tabel di atas, pertumbuhan ekonomi indonsia secara <em>year on year</em> jelas tidak terlalu fluktuatif dan bisa dibilang cukup stabil, namun jika pertumbuhan ekonomi indoneisa hanya sebatas itu negara indonesia akan tertinggal dengan negara berkembang lainnya di wilayah <em>ASEAN.</em></p>
</section>
<section id="metode-analisis" class="level2">
<h2 class="anchored" data-anchor-id="metode-analisis">3.2 Metode Analisis</h2>
<p>Metode analisi yang digunakan adalah kuantitatif , metode ini sendiri berfokus pada pengolahan data dari berbagai sumber di internet seperti BPS dan Bank Indonesia agar mendapatkan data yang akurat dalam format data persentase untuk kedua variabel yang dikaji agar lebih mudah untuk di plotting dan penelitian ini dibantu dengan R dan R studio dengan beberapa package yang digunakan seperti tidyverse,readxl,WDI,dan kableExtra. package ini sendiri memiliki fungsi untuk membantu user untuk melakukan plot dan regresi dan model yang digunakan hanya plotting biasa agar pembaca dapat memahami tabel plot tersebut.</p>
</section>
</section>
<section id="bab-iv-pembahasan" class="level1">
<h1>Bab IV Pembahasan</h1>
<section id="pembahasan-masalah" class="level2">
<h2 class="anchored" data-anchor-id="pembahasan-masalah">4.1 Pembahasan Masalah</h2>
<p>Dari data inflasi dan pertumbuhan ekonomi yang sudah diformat sesederhana mungkin, kita bisa melihat bahwa nilai inflasi yang terjadi tiap tahunnya yang begitu fluktuatif tidak memberikan dampak yang signifikan terhadap pertumbuhan ekonomi itu sendiri, mengapa begitu?, padalnya mau serendah ataupun setinggi apapun persentase inflasi pada tahun tersebut nilai pertumbuhan ekonomi tidak menurun lebih dari 4.8% dan tidak lebih tinggi dari 6.2% sekalipun saat itu inflasi sedang tinggi-tinginya yang mungkin bisa menyebabkan melemahnya mata uang di indonesia dan menyebabkan kurva permintaan menurun.</p>
</section>
<section id="analisis-masalah" class="level2">
<h2 class="anchored" data-anchor-id="analisis-masalah">4.2 Analisis Masalah</h2>
<p>&nbsp;Pada gambar di bawah kita bisa melihat Rplot yang dimana X berlaku sebagai nilai inflasinya dan Y berlaku sebagai nilai pertumbuhan ekonomi.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"inflasi.xlsx"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"inflasi"</span>,<span class="at">ylab=</span><span class="st">"pertumbuhan ekonomi"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="abxc_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"inflasi.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.4854 -0.2515 -0.1538  0.2667  0.8963 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  5.10842    0.31128  16.411 5.15e-08 ***
X            0.04542    0.06378   0.712    0.494    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4386 on 9 degrees of freedom
Multiple R-squared:  0.05334,   Adjusted R-squared:  -0.05184 
F-statistic: 0.5071 on 1 and 9 DF,  p-value: 0.4944</code></pre>
</div>
</div>
<p>dapat dilihat dari hasil regresi di atas bahwa nilai estimasi standar inflasi adalah 0.04542, ini berarti jika inflasi ingin naik 1% maka standar estimasi nya menyatakan bahwa setiap akan ada kenaikan atau penurunan inflasi akan menurun atau naik sebesar 0.04542 per kenaikan. dan residual of freedom nya hanya 0.4386 ini menandakan nilai ini moderat, ridak kuat dan tidak lemah</p>
</section>
</section>
<section id="bab-v-kesimpulan" class="level1">
<h1>Bab V Kesimpulan</h1>
<p>&nbsp; Dari hasil penelitian ini dapat disimpulkan bahwa, baik inflasi tersebut turun secara signifikan atau naik secara signifikan, tidak akan terlalu mempengaruhi nilai pertumbuhan ekonomi karena masih banyak faktor pendukung lain yang mempengaruhi perteumbuhan ekonomi tersebut</p>
</section>
<section id="daftar-pustaka" class="level1">
<h1>Daftar Pustaka</h1>
<p>Ardiansyah, H. (2017). PENGARUHsINFLASI TERHADAP PERTUMBUHANnEKONOMI DIyINDONESIA.</p>
<p>Br Simanungkalit, E. F. (2020). PENGARUH INFLASI TERHADAP PERTUMBUHAN EKONOMI DI INDONESIA. <em>JOURNAL OF MANAGEMENT</em> .</p>
<p>Salim, A., Purnama sari, A., &amp; Fadilla, F. (2021). Pengaruh Inflasi Terhadap Pertumbuhan Ekonomi Indonesia. <em>Ekonomica Sharia: Jurnal Pemikiran Dan Pengembangan Ekonomi Syariah</em>.</p>
<section id="section-1" class="level2">
<h2 class="anchored" data-anchor-id="section-1"></h2>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>